[package]
name = "pv_leopard_filedemo"
version = "1.0.1"
edition = "2018"

[dependencies]
chrono = "0.4.20"
clap = "3.2.16"
hound = "3.4.0"
itertools = "0.10.3"
pv_leopard = "=1.1.0"
tabwriter = "1.2.1"
