[package]
name = "pv_leopard_filedemo"
version = "1.0.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
hound = "3.4.0"
itertools = "0.10.1"
pv_leopard = { path = "../../../binding/rust" }
