-keep class ai.picovoice.leopard.*Exception { <init>(...); }
-keep class ai.picovoice.leopard.LeopardTranscript { <init>(...); }
-keep class ai.picovoice.leopard.LeopardTranscript$Word { <init>(...); }
