source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'LeopardAppTest' do
  pod 'Leopard-iOS', '~> 1.0.1'
end

target 'LeopardAppTestUITests' do
  pod 'Leopard-iOS', '~> 1.0.1'
end

target 'PerformanceTest' do
  pod 'Leopard-iOS', '~> 1.0.1'
end
