[package]
name = "pv_leopard_micdemo"
version = "2.0.1"
edition = "2018"

[dependencies]
chrono = "0.4.20"
clap = "3.2.16"
ctrlc = "3.2.2"
hound = "3.4.0"
itertools = "0.10.3"
pv_leopard = "=2.0.1"
pv_recorder = "=1.2.1"
tabwriter = "1.2.1"
