name: Run demo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  model_path:
    required: true
  init_performance_threshold_sec:
    required: false
    type: number
  process_performance_threshold_sec:
    required: false
    type: number

runs:
  using: "composite"
  steps:
  - run: >
      ./build/leopard_demo
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }} 
      ../../resources/audio_samples/test.wav
    if: "${{ inputs.init_performance_threshold_sec == '' || inputs.process_performance_threshold_sec == ''}}"
    working-directory: demo/c
    shell: bash

  - run: >
      ./build/leopard_demo
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      -i ${{ inputs.init_performance_threshold_sec }}
      -p ${{ inputs.proc_performance_threshold_sec }}
      ../../resources/audio_samples/test.wav
    if: "${{ inputs.init_performance_threshold_sec != '' && inputs.process_performance_threshold_sec != ''}}"
    working-directory: demo/c
    shell: bash
  