source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'LeopardDemo' do
  pod 'Leopard-iOS', podspec: 'https://raw.githubusercontent.com/Picovoice/leopard/v1.1-ios/binding/ios/Leopard-iOS.podspec'
end
