name: leopard_demo
description: Demonstrates how to use the leopard plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.0.9

  flutter_voice_processor: ^1.0.6

  leopard_flutter:
    path: ../../binding/flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:  
  uses-material-design: true
  assets:
    - assets/contexts/android/leopard_params.pv
    - assets/contexts/ios/leopard_params.pv
