name: Android AppCenter Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/android/LeopardTestApp/**'
      - '.github/workflows/android-appcenter.yml'
      - 'resources/audio_samples/**'
      - 'resources/.test/**'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/android/LeopardTestApp/**'
      - '.github/workflows/android-appcenter.yml'
      - 'resources/audio_samples/**'
      - 'resources/.test/**'

defaults:
  run:
    working-directory: binding/android/LeopardTestApp

jobs:
  build:
    name: Run Android Tests on AppCenter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Binding pre-build
      run: ./gradlew assemble

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Android keystore variables
      run: |
        echo storePassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyPassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyAlias=picovoice >> local.properties
        echo storeFile=../picovoice.jks >> local.properties

    - name: Setup Android keystore file
      run: echo "${{secrets.ANDROID_RELEASE_KEYSTORE_FILE_B64}}" | base64 -d > picovoice.jks

    - name: Build app
      run: ./gradlew assembleEnDebug

    - name: Build androidTest
      run: ./gradlew assembleEnDebugAndroidTest

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Leopard-Android"
        --devices "Picovoice/android-min-max"
        --app-path leopard-test-app/build/outputs/apk/en/debug/leopard-test-app-en-debug.apk
        --test-series "leopard-android"
        --locale "en_US"
        --build-dir leopard-test-app/build/outputs/apk/androidTest/en/debug

  build-integ:
    name: Run Android Integration Tests on AppCenter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Android keystore variables
      run: |
        echo storePassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyPassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyAlias=picovoice >> local.properties
        echo storeFile=../picovoice.jks >> local.properties

    - name: Setup Android keystore file
      run: echo "${{secrets.ANDROID_RELEASE_KEYSTORE_FILE_B64}}" | base64 -d > picovoice.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleEnRelease

    - name: Build androidTest
      run: ./gradlew assembleEnReleaseAndroidTest -DtestBuildType=integ

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Leopard-Android
        --devices "Picovoice/android-min-max"
        --app-path leopard-test-app/build/outputs/apk/en/release/leopard-test-app-en-release.apk
        --test-series "leopard-android"
        --locale "en_US"
        --build-dir leopard-test-app/build/outputs/apk/androidTest/en/release

