name: Android AppCenter Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/android/LeopardDemo/**'
      - '!demo/android/LeopardDemo/README.md'
      - '.github/workflows/android-appcenter.yml'
      - 'resources/audio_samples/**'
      - 'resources/test/**'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/android/LeopardDemo/**'
      - '!demo/android/LeopardDemo/README.md'
      - '.github/workflows/android-appcenter.yml'
      - 'resources/audio_samples/**'
      - 'resources/test/**'

defaults:
  run:
    working-directory: demo/android/LeopardDemo

jobs:
  build:
    name: Run Android Tests on AppCenter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Binding pre-build
      run: ./gradlew assemble
      working-directory: binding/android

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleAndroidTest

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Leopard-Android"
        --devices "Picovoice/android-min-max"
        --app-path leopard-demo-app/build/outputs/apk/debug/leopard-demo-app-debug.apk
        --test-series "leopard-android"
        --locale "en_US"
        --build-dir leopard-demo-app/build/outputs/apk/androidTest/debug
