name: Android Performance

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'
  pull_request:
    branches: [ master ]
    paths: 
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'

defaults:
  run:
    working-directory: demo/android/LeopardDemo
    
jobs:
  build:
    name: Run Android Speed Tests on AppCenter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [single-android, 32bit-android]
        include:
        - device: single-android
          initPerformanceThresholdSec: 3.0
          procPerformanceThresholdSec: 0.5
        - device: 32bit-android
          initPerformanceThresholdSec: 7.0
          procPerformanceThresholdSec: 1.75

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    
    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Copy test_resources
      run: ./copy_test_resources.sh
    
    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Number of Iterations
      run: echo numTestIterations="30" >> local.properties

    - name: Inject Init Performance Threshold
      run: echo initPerformanceThresholdSec="${{ matrix.initPerformanceThresholdSec }}" >> local.properties

    - name: Inject Proc Performance Threshold
      run: echo procPerformanceThresholdSec="${{ matrix.procPerformanceThresholdSec }}" >> local.properties
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build app
      run: ./gradlew assembleDebug
    
    - name: Build androidTest
      run: ./gradlew assembleAndroidTest
    
    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Leopard-Android"
        --devices "Picovoice/${{ matrix.device }}"
        --app-path leopard-demo-app/build/outputs/apk/debug/leopard-demo-app-debug.apk
        --test-series "leopard-android"
        --locale "en_US"
        --build-dir leopard-demo-app/build/outputs/apk/androidTest/debug

