name: C Demos

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'
      - 'include/**'
      - 'lib/beaglebone/**'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
  pull_request:
    branches: [master]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'
      - 'include/**'
      - 'lib/beaglebone/**'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'

defaults:
  run:
    working-directory: .

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: CMake
      run: cmake -S demo/c/ -B demo/c/build

    - name: Build
      run: cmake --build demo/c/build

    - name: Test
      run: |
        ./demo/c/build/leopard_demo \
        -a ${{secrets.PV_VALID_ACCESS_KEY}} \
        -l lib/linux/x86_64/libpv_leopard.so \
        -m lib/common/leopard_params.pv \
        resources/audio_samples/test.wav

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: CMake
      run: cmake -S demo/c/ -B demo/c/build

    - name: Build
      run: cmake --build demo/c/build

    - name: Test
      run: |
        ./demo/c/build/leopard_demo \
        -a ${{secrets.PV_VALID_ACCESS_KEY}} \
        -l lib/mac/x86_64/libpv_leopard.dylib \
        -m lib/common/leopard_params.pv \
        resources/audio_samples/test.wav

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: CMake
      run: cmake -S demo/c/ -B demo/c/build -G "MinGW Makefiles"

    - name: Build
      run: cmake --build demo/c/build

    - name: Test
      run: |
        demo\\c\\build\\leopard_demo.exe \
        -a ${{secrets.PV_VALID_ACCESS_KEY}} \
        -l lib/mac/x86_64/libpv_leopard.dylib \
        -m lib/common/leopard_params.pv \
        resources/audio_samples/test.wav
