name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/dotnet/**'
      - '!binding/dotnet/README.md'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/audio_samples/**'
      - 'resources/test/**'
      - '.github/workflows/dotnet.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/dotnet/**'
      - '!binding/dotnet/README.md'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/audio_samples/**'
      - 'resources/test/**'
      - '.github/workflows/dotnet.yml'

defaults:
  run:
    working-directory: binding/dotnet

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}
    env:
      ACCESS_KEY: ${{secrets.PV_VALID_ACCESS_KEY}}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: [3.0.x, 3.1.x, 5.0.x, 6.0.x, 7.0.x]
        include:
          - dotnet-version: 3.0.x
            dotnet-framework: netcoreapp3.0
          - dotnet-version: 3.1.x
            dotnet-framework: netcoreapp3.1
          - dotnet-version: 5.0.x
            dotnet-framework: net5.0
          - dotnet-version: 6.0.x
            dotnet-framework: net6.0
          - dotnet-version: 7.0.x
            dotnet-framework: net7.0
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --framework ${{ matrix.dotnet-framework }}

    - name: Test
      run: dotnet test --framework ${{ matrix.dotnet-framework }}

  build-self-hosted:
    runs-on: ${{ matrix.machine }}
    env:
      ACCESS_KEY: ${{secrets.PV_VALID_ACCESS_KEY}}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]

    steps:
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --framework net6.0

    - name: Test
      run: dotnet test --framework net6.0
