name: iOS Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/ios/LeopardDemo/**'
      - '.github/workflows/ios-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/ios/LeopardDemo/**'
      - '.github/workflows/ios-demos.yml'

defaults:
  run:
    working-directory: demo/ios/LeopardDemo

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build English
        run: xcrun xcodebuild build
          -configuration Debug
          -project LeopardDemo.xcodeproj
          -sdk iphoneos
          -scheme _enDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Build Other Language
        run: xcrun xcodebuild build
          -configuration Debug
          -project LeopardDemo.xcodeproj
          -sdk iphoneos
          -scheme koDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO
