name: Node.js Performance

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/nodejs/.test/perf.test.ts'
      - 'lib/common/**'
      - 'lib/node/**'
      - '.github/workflows/nodejs-perf.yml'

  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/nodejs/.test/perf.test.ts'
      - 'lib/common/**'
      - 'lib/node/**'
      - '.github/workflows/nodejs-perf.yml'

defaults:
  run:
    working-directory: binding/nodejs

jobs:
  perf-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          init_performance_threshold_sec: 2.5
          proc_performance_threshold_sec: 0.9
        - os: windows-latest
          init_performance_threshold_sec: 2.5
          proc_performance_threshold_sec: 1.1
        - os: macos-latest
          init_performance_threshold_sec: 4.0
          proc_performance_threshold_sec: 2.0


    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: yarn install

    - name: Test
      run: yarn test test/perf.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --num_test_iterations=50 --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} --proc_performance_threshold_sec=${{matrix.proc_performance_threshold_sec}}

  perf-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      fail-fast: false
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64]
        include:
        - machine: rpi3-32
          init_performance_threshold_sec: 7.6
          proc_performance_threshold_sec: 4.5
        - machine: rpi3-64
          init_performance_threshold_sec: 8.4
          proc_performance_threshold_sec: 4.5
        - machine: rpi4-32
          init_performance_threshold_sec: 5.7
          proc_performance_threshold_sec: 3.3
        - machine: rpi4-64
          init_performance_threshold_sec: 5.1
          proc_performance_threshold_sec: 3.2
        - machine: rpi5-64
          init_performance_threshold_sec: 3.0
          proc_performance_threshold_sec: 1.5

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install

    - name: Machine state before
      working-directory: resources/scripts
      run: bash machine-state.sh

    - name: Test
      run: yarn test test/perf.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --num_test_iterations=20 --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} --proc_performance_threshold_sec=${{matrix.proc_performance_threshold_sec}}

    - name: Machine state after
      working-directory: resources/scripts
      run: bash machine-state.sh
