name: Python Performance

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/python-perf.yml'
      - 'binding/python/test_leopard_perf.py'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/python-perf.yml'
      - 'binding/python/test_leopard_perf.py'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'

defaults:
  run:
    working-directory: binding/python

jobs:
  perf-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006
        - os: windows-latest
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006
        - os: macos-latest
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Test
      run: python3 test_leopard_perf.py ${{secrets.PV_VALID_ACCESS_KEY}} 50 ${{matrix.init_performance_threshold_sec}} ${{matrix.proc_performance_threshold_sec}}

  perf-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      fail-fast: false
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]
        include:
        - machine: rpi3-32
          num_test_iterations: 20
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006
        - machine: rpi3-64
          num_test_iterations: 20
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006
        - machine: rpi4-32
          num_test_iterations: 20
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006
        - machine: rpi4-64
          num_test_iterations: 20
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006
        - machine: jetson
          num_test_iterations: 20
          init_performance_threshold_sec: 0.006
          proc_performance_threshold_sec: 0.006

    steps:
    - uses: actions/checkout@v2

    - name: Machine state before
      working-directory: resources/scripts
      run: bash machine-state.sh

    - name: Test
      run: python3 test_leopard_perf.py ${{secrets.PV_VALID_ACCESS_KEY}} ${{matrix.num_test_iterations}} ${{matrix.init_performance_threshold_sec}} ${{matrix.proc_performance_threshold_sec}}

    - name: Machine state after
      working-directory: resources/scripts
      run: bash machine-state.sh
