name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/rust.yml'
      - 'binding/rust/**'
      - '!binding/rust/README.md'
      - 'lib/common/**'
      - 'lib/jetson/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/audio_samples/**'
      - 'resources/.test/**'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/rust.yml'
      - 'binding/rust/**'
      - '!binding/rust/README.md'
      - 'lib/common/**'
      - 'lib/jetson/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/audio_samples/**'
      - 'resources/.test/**'


env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: binding/rust
    shell: bash

jobs:
  # build-github-hosted:
  #   runs-on: ${{ matrix.os }}
  #   env:
  #     ACCESS_KEY: ${{secrets.PV_VALID_ACCESS_KEY}}

  #   strategy:
  #     matrix:
  #       os: [windows-latest]

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Rust pre-build
  #     run: bash copy.sh

  #   # - name: Rust dependencies
  #   #   if: matrix.os == 'ubuntu-latest'
  #   #   run: sudo apt install libasound2-dev -y

  #   - name: Install stable toolchain
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       profile: default
  #       toolchain: 1.61.0
  #       override: true

  #   - name: Rust build
  #     run: cargo build --verbose

  #   - name: Rust run tests
  #     run: cargo test --verbose

  build-self-hosted:
    runs-on: ${{ matrix.machine }}
    env:
      ACCESS_KEY: ${{secrets.PV_VALID_ACCESS_KEY}}

    strategy:
      matrix:
        machine: [pv-windows]

    steps:
    - uses: actions/checkout@v3

    - name: Rust pre-build
      run: bash copy.sh

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Rust build
      run: cargo build --verbose

    - name: Rust run tests
      run: cargo test --verbose -- --test-threads 1
